import { PON } from "./func/power-of-num.js";
import { isSum } from "./func/is-sum-n.js";
import { Greet } from "./func/name.greet.js";
import { areaofTriangle } from "./func/areaofTriangle.js";
import { isPrime } from "./func/find-prime-num.js";
import { areaofCircle } from "./func/areaofCircle.js";
import { numberOfLegs } from "./func/numberOfLegs.js";
import { circleVSsquare } from "./func/diameter-side.js";
// console.log(PON(2, 10));
// console.log(isSum(2, 3, 5));
// console.log(Greet("Tauseef", 23));
// console.log(areaofTriangle(20, 40));
// console.log("prime=", isPrime(27));
// console.log(areaofCircle(2));
// console.log(findLegs(4, 8, 6));
console.log(circleVSsquare(4, 16));
